### PR TITLE
Update tests to cucumber

### PR DESCRIPTION
**Pull request by pzavolinsky**
### Changes
Replaces the `jasmine` test runner for `cucumber`, migrates all tests to a more readable gherkin version.

Rather than having something cryptic like: 

```js
  itIs('all', ['./import-star.ts', './import-default.ts'], []);
```

We now have:

```gherkin
Scenario: Unused export const
  Given file "a.ts" is export const a = 1;
  When analyzing "tsconfig.json"
  Then the result at a.ts is ["a"]
```

With this in place, writing new tests (in TDD fashion) to cover more cases and/or document bugs, regressions and missing features should be a lot less painful.

More documentation here:
- [Gherkin syntax](https://cucumber.io/docs/gherkin/reference/)
- [picked-cucumber](https://github.com/muralco/pickled-cucumber#picked-cucumber)

### CODE REVIEW

**Comment by mrseanryan** [comment]
hi @pzavolinsky the new format is much nicer !

One thing - it seems difficult to see if all the old tests are migrated, as the new format is completely different.

For example I think the 2 tests about `--ignorePaths` are missing.

Is there some way to make comparing the old vs new a bit easier,
for example what about using the same file names as the old tests ?

One other (small) thing - the output has a lot of helper text (`Step reference`) but I couldn't see how to disable it...

Regards,
Sean

**Comment by pzavolinsky** [comment]
we can toggle `usage: true` based on  `process.env.USAGE` for instance. Then you would run `USAGE=1 npm run test`.

**Comment by pzavolinsky** [comment]
Regarding the test migration, you are 100% right, I'm going to manually recheck those. And we could also add `nyc` to actually check code/branching coverage (with that, we can actually monitor if we are missing a test case).

**Comment by mrseanryan** [comment]
(related) I found the option `ignorePaths` (added by me!) was not quite working correctly.

So it might be an idea to process that PR first - https://github.com/pzavolinsky/ts-unused-exports/pull/56

**Comment by pzavolinsky** [comment]
@mrseanryan I've updated this PR to latest TS and migrated the `---ignorePaths` tests. Please take another look and let me know.

Unrlated, I upgraded `tslint` and added an `npm run lint` script. There are several linting issues but we should fix them all in a separate PR (ideally just put `prettier` and forget about it). For now `tslint` will work, but we should also look into moving to `eslint`

Cheers!

**Comment by mrseanryan** [comment]
hi @pzavolinsky  looks good and complete, as far as I can see.

We could add 1 more simple test, where 1 export is unused, and 1 unused:

(the original tests seem to have a few of those)

```ts
Scenario: One unused export const
  Given file "a.ts" is 
    """
    export const a = 1;
    export const b = 1;
    """
  And file "b.ts" is import { a } from './a';
  When analyzing "tsconfig.json"
  Then the result at a.ts is ["b"]

```

Could also delete `import-spec.js`

There are a few `@Ignore`d tests but they look like new ones, so probably can be fixed later.

**Comment by mrseanryan** [comment]
Assuming `app-spec.js` is staying, then can delete all `data` except for:

- `data/tsconfig-with-comments.json`
- `data/tsconfig-include.json`

**Comment by mrseanryan** [comment]
@pzavolinsky if you want, I can help with this PR?

**Comment by pzavolinsky** [comment]
> Assuming app-spec.js is staying...

Actually the new tests are fully equipped to model those tests as well [see this one](https://github.com/pzavolinsky/ts-unused-exports/pull/49/files#diff-205d77dc77939f2ca774f44c8a5ce6c8R4)

> if you want, I can help with this PR?

That would be great @mrseanryan , please make it your own :) If you could directly add the tests you thing we are missing and also the 2 tests for `app-spec.js` we could remove the `specs` dir and `npm remove jasmine`.

**Comment by mrseanryan** [comment]
hi @pzavolinsky  - have pushed those changes.

I will try to investigate the `@ignore`d tests ...

Sean

**Comment by mrseanryan** [comment]
@pzavolinsky have fixed the failing tests.

- tested against large codebase (150k lines) - is OK
- added a npm task to run only some tests '@only' which helps for debugging

I think this PR is good to go 😃

**Comment by pzavolinsky** [comment]
Awesome, I'll merge it in a minute.

> added a npm task to run only some tests '@only' which helps for debugging

There is a (somewhat hidden) way to do this with `npm run test:unit features/path/to/file.feature` (run all tests in that file) and `npm run test:unit features/path/to/file.feature:123` (only the test whose `Scenario: ...` is defined in line `123`).

**Comment by pzavolinsky** [comment]
Merged (`3.0.2`). Thanks @mrseanryan !

This PR marks a great milestone for us.

From now on, for every bug report (except the "in a huge codebase I get an out-of-memory error") we should be able to write the repro test in a `feature` before even fixing the code.

We can even accept PRs that only add the repro tests (without the fix) and use that as a guide (like I did with the `@ignore` ones you just fixed).

If every bug gets at repro scenario in a featur, we can make sure we'll never have a regression on that bug.

I'm a big fan of this type of TDD and I've been using it in my other projects for a while now (e.g. https://github.com/muralco/mural-schema/tree/master/features).

`ts-unused-exports` was suffering from my busy schedule and lack of attention and it great to have you onboard Sean!

**Comment by mrseanryan** [comment]
Thats great, happy to help :) 
Sean

Sent from Yahoo Mail on Android 
 
  On Mon, 28 Oct 2019 at 18:23, Patricio Zavolinsky<notifications@github.com> wrote:   
Merged (3.0.2). Thanks @mrseanryan !

This PR marks a great milestone for us.

From now on, for every bug report (except the "in a huge codebase I get an out-of-memory error") we should be able to write the repro test in a feature before even fixing the code.

We can even accept PRs that only add the repro tests (without the fix) and use that as a guide (like I did with the @ignore ones you just fixed).

If every bug gets at repro scenario in a featur, we can make sure we'll never have a regression on that bug.

I'm a big fan of this type of TDD and I've been using it in my other projects for a while now (e.g. https://github.com/muralco/mural-schema/tree/master/features).

ts-unused-exports was suffering from my busy schedule and lack of attention and it great to have you onboard Sean!

**Pull request merged**
