### PR TITLE
Update TypeScript dependency to 3.6.4

### PR DESCRIPTION
**Pull request by mrseanryan**
Update **TypeScript** dependency to 3.6.4

- tested on large codebase (~150k lines) - no observed difference in behavior
- solves #33

### CODE REVIEW

**Comment by mrseanryan** [comment]
I think is good to go.

Could be good to up the major version, in case some users still on TypeScript 2.x ?

**Comment by pzavolinsky** [comment]
@mrseanryan I'll push master to NPM as-is, and then merge this PR bumping the major.

After this, fixes to older TS versions will be painful so we should keep them to a minimum if possible.

**Comment by pzavolinsky** [comment]
Done, master is `2.2.0` (old TS). I'm merging this PR and bumping again

**Comment by pzavolinsky** [comment]
Done, master is `3.0.0` (new TS). If we really need to maintain 2.x, I pushed a branch called `release/2.x.x`.

**Pull request merged**
