### PR TITLE
Add support for dynamic imports

### PR DESCRIPTION
**Pull request by mrseanryan**
- when a node may contain a dynamic import keyword, then scan recursively for nodes that have an `import` expression.

Refactoring:
- extract functions out of the large `map()`
- extract parser code out to separate files, by responsibility (import/export/comments etc.)

Addresses issue #13

### CODE REVIEW

**Comment by mrseanryan** [comment]
TODO:

* [ ] test on large code-base
* [ ] rebase onto master, after #70 is merged (this PR is based on that, to avoid merge conflicts)

**Comment by mrseanryan** [comment]
@pzavolinsky this is ready, far as I can tell.

- tested on large codebase: performance basically same
- adds unit tests for dynamic imports
- refactoring: extracting smaller files out of the main parser.ts

note: the codebases I work on, don't really use dynamic imports. So am relying on the unit tests.

But I think this is good enough.

**Comment by pzavolinsky** [comment]
@mrseanryan code is looking good, the only thing I would change is:
- move `parser.ts` to `parser/index.ts`
- move all `parser.*.ts` to `parser/*.ts`

After that change, could you squash (to drop commits that only remove comments, like the `TODO` one)?

**Comment by mrseanryan** [comment]
done!

**Comment by mrseanryan** [comment]
@pzavolinsky  hope you don't mind - but merged it (with the changes)

so then frees up the next PR

**Comment by pzavolinsky** [comment]
:+1:

**Pull request merged**
