### PR TITLE
check for .d.ts files for path aliases

### PR DESCRIPTION
**Pull request by davidparkagoda**
Summary:

Tries to fix a bug where there are false positives, if importing from a d.ts file.
This only occurs if tsconfig uses aliases (paths).

This PR would need another PR to be merged in
https://github.com/dividab/tsconfig-paths/pull/124

Right now tsconfig-paths is returning file paths with the extension stripped, `src/something/hi.ts` => `src/something/hi`. 
However this extension stripping only removes 1 level of `.` so when we matched `.d.ts` files it will incorrectly strip the extension to be like `src/something/hi.d.ts` => `src/something/hi.d`.

### CODE REVIEW

**Comment by mrseanryan** [comment]
hi @davidparkagoda  

question - 
as an alternative to waiting for the `ts-config-paths` PR,
could we 'patch' our code to get around this:

> will incorrectly strip the extension to be like src/something/hi.d.ts => src/something/hi.d.

We could add a TODO to remove our 'patch' once `ts-config-paths` is updated.

**Comment by davidparkagoda** [comment]
Yes we could definitely do that but it does not feel great.

Even if we do this 'patch', the workarounds that I see are not great.

We could do something like
`matchedPath.replace(/\.d$/, '')` but that seems a bit too broad.
or
after we get the `matchedPath` we check if the file exists `matchPath + '.ts'` but that is an extra file check.

If you are okay with one of those solutions or have a better workaround I am willing to make the change

**Comment by mrseanryan** [comment]
| We could do something like
| matchedPath.replace(/\.d$/, '') but that seems a bit too broad.

I think this would work?

Or - in which cases would this cause a problem ?

**Comment by davidparkagoda** [comment]
I know this is kind of edge case but a files named like

`file.d.tsx`
`file.d.js`
`file.d.jsx`

**Comment by mrseanryan** [comment]
Hmm wouldn't that also happen with the fix for tsconfig-paths?

**Comment by davidparkagoda** [comment]
No. 

When `tsconfig-paths` is iterating the list of extensions that we pass to it, I modified it so that it will note the extension length of the matched path when found. This is make it so that we only strip out the length of the of the matched extension.


You will not be able to have the same kind of "bug" with the fix for `tsconfig-paths` without having a really weird webpack or configuration

`const EXTENSIONS = ['.d.ts', '.ts', '.tsx', '.d.js', '.js', '.jsx'];`
Now if you imported `file`, which through weird configuration, points to `file.d.js`, `tsconfig-paths` will return `file` which is correct given the extensions that we passed to `tsconfig-paths`

However if you imported `file.d`, `tsconfig-paths` will try 
`'file.d' + '.d.js'`, which does not exist
`'file.d' + `.js'` which does exist. `tsconfig-paths` also knows the matched extension so it only strips `.js`

**Comment by mrseanryan** [comment]
I see. So tsconfig-paths checks for file exists.

Question is that covered by this approach:

> after we get the matchedPath we check if the file exists matchPath + '.ts' but that is an extra file check.

**Comment by davidparkagoda** [comment]
yes this would work. something like

```
if (matchedPath.endsWith('.d')) {
    if (matchedPath + '.ts') file exists {
        matchedPath = matchedPath.slice(0, -2);
    }
}
```

**Comment by mrseanryan** [comment]
@davidparkagoda so is this PR completed ?
(it looks good to me).

If so, can you please squash it down to 1 commit.

Or let me know if you want me to do it ...

Thanks,
Sean

**Comment by davidparkagoda** [comment]
@mrseanryan yup everything looks good. Please go ahead and do anything to get this merged in :D

**Comment by mrseanryan** [comment]
@davidparkagoda  
Merged it to master (used a separate PR due to some github/travis glitch).
Hopefully it will be released soon.

Thank you for your contribution !

**Pull request closed without merging**
