### PR TITLE
Add more badges

### PR DESCRIPTION
**Pull request by mrseanryan**
Add some more badges that seem useful: [#73]

- code coverage
- dependencies state
- npm version
- downloads
- license

Looks like this:

image

ALSO adds `node 12` to the list of Node versions to run by Travis.

### CODE REVIEW

**Comment by mrseanryan** [comment]
TODO - get code coverage badge working ...

Uses `coveralls.io`

**Comment by mrseanryan** [comment]
note: this is based on PR #74 

So I guess that one should merge first.

**Comment by mrseanryan** [comment]
@pzavolinsky of you like, email notifications from travis can be turned off in travis yml:

```
notifications:
    email: false
```

**Comment by pzavolinsky** [comment]
>  email notifications from travis can be turned off in travis yml

Can you add it to this PR?

**Comment by pzavolinsky** [comment]
Also, I've already merged #74, you can rebase after `master`.

**Comment by mrseanryan** [comment]
@pzavolinsky  disabling travis emails, and rebased. thanks!

**Pull request merged**
