### PR TITLE
fix: file ending with 'index.ts' will always be reported as containin…

### LINKED ISSUE #220: bug: file ending with 'index.ts' will always be reported as containing unused exports
In my project, I have a file where its name ends with `index.ts`. Although all of its exports were imported elsewhere, `ts-unused-exports` reports the file as containing unused exports.

### PR DESCRIPTION
**Pull request by wongjiahau**
Fixes #220

### CODE REVIEW

**Comment by mrseanryan** [comment]
@wongjiahau  thank you for contributing!

note: unfortunately the merge/release process is very slow at the moment.

One suggestion: would it make sense to just have 1 PR?   so combine this with #223

**Comment by wongjiahau** [comment]
My pleasure, @mrseanryan. I thought of that earlier. However, though the two fixes look similar, they solve very different bugs, so I decided to keep them separate.

**Comment by mrseanryan** [comment]
hi @wongjiahau oh in that case 2 separate PRs is fine

sean

**Comment by mrseanryan** [comment]
@wongjiahau  merged!
thank you for this contribution 👍 

sean

**Pull request merged**
