### PR TITLE
Fix: Destructured exports with renaming.

### PR DESCRIPTION
**Pull request by ksr79**
PR 120 fixes destructuring exports in general, but not when they are renamed in the course of destructuring. This PR tries to adapt that behaviour.

### CODE REVIEW

**Comment by mrseanryan** [comment]
@ksr79  looks good!

Can you please add an entry to CHANGELOG.md

**Comment by mrseanryan** [comment]
@pzavolinsky it looks like Travis is stuck again.

If you want, I can rebuild this PR, with a CHANGELOG entry, and just merge it?

**Comment by mrseanryan** [comment]
@ksr79  @pzavolinsky 

about the travis problem.

It seems that no build actually ran for this PR ?

https://travis-ci.com/pzavolinsky/ts-unused-exports/builds/

Maybe, the travis build only works for accounts that are 'collaborator' or 'owner' of the git repo ?

But there must be some way to configure it 🤔

**Comment by mrseanryan** [comment]
@pzavolinsky is the 'remedy' mentioned here at all relevant?

https://github.com/travis-ci/travis-ci/issues/10204

**Comment by pzavolinsky** [comment]
I've just removed the status check and add it again and now looks like it's working.

**Pull request merged**
