### PR TITLE
Add support for import with @ prefix - #266

### PR DESCRIPTION
**Pull request by mrseanryan**
Add support for import with @ prefix - #266

Import statements like this are not handled, so usages are not picked up:

import { foo } from "@foo/index";
note: usages like the following ARE supported:

import { foo } from "./foo/index";

---

TODO

* [skipped] get the JavaScript executing to make sure the example is correct
* [x] repro
* [x] add support for import when the imported file is `index.ts` (or index.x ...)
* [x] check against related issues with index: #154 #220 #222
* [x] test/release

### CODE REVIEW

**Comment by mrseanryan** [comment]
@aryzing 

I could use some help to get this set up.

I want to execute the compiled JavaScript to make sure the example here is correct.

Problem: node seems to be having a similar problem as `ts-unused-exports` - it does not understand the import with `@` prefix:

```
cd ./example/path-alias-and-sub-folders-2 
./execute.sh
```

output:

```
...


node:internal/errors:491
    ErrorCaptureStackTrace(err);
    ^

Error [ERR_MODULE_NOT_FOUND]: Cannot find package '@foo/index' imported from /Users/Sean.Ryan/src/github/other/ts-unused-exports/example/path-alias-and-sub-folders-2/dist/index.js
    at new NodeError (node:internal/errors:400:5)
    at packageResolve (node:internal/modules/esm/resolve:889:9)
    at moduleResolve (node:internal/modules/esm/resolve:938:20)
    at defaultResolve (node:internal/modules/esm/resolve:1153:11)
    at nextResolve (node:internal/modules/esm/loader:163:28)
    at ESMLoader.resolve (node:internal/modules/esm/loader:842:30)
    at ESMLoader.getModuleJob (node:internal/modules/esm/loader:424:18)
    at ModuleWrap.<anonymous> (node:internal/modules/esm/module_job:77:40)
    at link (node:internal/modules/esm/module_job:76:36) {
  code: 'ERR_MODULE_NOT_FOUND'
}

Node.js v18.13.0
```

**Comment by mrseanryan** [comment]
Compiling the example passes:
```
    "build": "tsc -p ./tsconfig.json",
``

BUT trying to execute the JavaScript fails:
```
    "start": "npm run-script build && node ./dist/index.js",
```

**Comment by mrseanryan** [comment]
@aryzing - UPDATED
Indeed, the problem is the file being imported is `index`
Another very similar file `other` works OK.

Perhaps this is another #154 but for simplicity I am treating as a separate PR/issue.

**Comment by aryzing** [comment]
Not sure if you managed to figure it out? If not, you can use `tsc-alias` to convert aliases to system paths,

```
pnpn add tsc-alias
```

`"build": "tsc && tsc-alias"`

**Comment by mrseanryan** [comment]
> 

thank you - hope to have a fix later this week …

**Comment by mrseanryan** [comment]
So, the handling of import from `x/index.x` files was buggy.

- improved support for imports like:

import * as x from "foo";
import * as x from "foo/index";

with support for various file extensions.

- added more test cases to cover

**Pull request merged**
